In [79]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes

In [80]:
X, y = load_diabetes(return_X_y=True)

In [81]:
X.shape

(442, 10)

In [82]:
y.shape

(442,)

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [84]:
lr=LinearRegression()

In [85]:
lr.fit(X_train,y_train)

LinearRegression()

In [86]:
y_pred=lr.predict(X_test)

In [87]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [88]:
lr.intercept_

np.float64(151.88331005254167)

In [89]:
r2_score(y_test,y_pred)

0.4399338661568968

In [103]:
import random

class MBGD:

    def __init__(self,batch_size,learning_rate=0.01,epochs=100):

        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size

    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):

            for j in range(int(X_train.shape[0]/self.batch_size)):

                idx = random.sample(range(X_train.shape[0]),self.batch_size)

                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)

        print(self.intercept_,self.coef_)

    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [104]:
mb=MBGD(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [105]:
mb.fit(X_train,y_train)

151.01317356428433 [  32.65626122 -142.89444274  445.64451184  307.53964591  -23.49044515
  -93.98962628 -189.96629673  114.31093127  407.28186666  118.89135887]


In [106]:
y_pred=mb.predict(X_test)

In [107]:
r2_score(y_test,y_pred)

0.4526361174524701

**Applying SkLearn SGD**

In [108]:
from sklearn.linear_model import SGDRegressor

In [134]:
reg=SGDRegressor(learning_rate='constant',eta0=0.1)

In [135]:
batch_size = 100

for i in range(100):

    idx = random.sample(range(X_train.shape[0]),batch_size)
    reg.partial_fit(X_train[idx],y_train[idx])

In [136]:
reg.coef_

array([  26.15525538, -178.04784273,  471.61468343,  313.7061435 ,
        -38.93083881, -111.19933043, -206.05357377,  100.70528152,
        443.89926366,   97.95235498])

In [137]:
reg.intercept_

array([165.8386737])

In [138]:
y_pred=reg.predict(X_test)

In [139]:
r2_score(y_test,y_pred)

0.4244190759351407